/**
 * Created by isp on 9/29/17.
 */

export const HANDLE_NEXT = 'HANDLE_NEXT';
export const HANDLE_PREVIOUS = 'HANDLE_PREVIOUS';
export const UPDATE_CSV_LIST = 'UPDATE_CSV_LIST';
export const UPDATE_CSV_ACTIVE_VALUE = 'UPDATE_CSV_ACTIVE_VALUE';
export const UPDATE_TEXT_INPUT_LINK = 'UPDATE_TEXT_INPUT_LINK';
export const UPDATE_TEXT_INPUT_VALUE = 'UPDATE_TEXT_INPUT_VALUE';